# Generated by Django 2.2.1 on 2019-05-06 02:35

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(max_length=20, null=True, verbose_name='昵称')),
                ('avatar', models.ImageField(upload_to='', verbose_name='头像')),
                ('sex', models.SmallIntegerField(choices=[(0, '女'), (1, '男'), (2, '保密')], default=2, verbose_name='性别')),
                ('mobile', models.CharField(max_length=11, null=True, verbose_name='手机')),
                ('birthday', models.DateField(null=True, verbose_name='生日')),
                ('pay_pwd', models.CharField(max_length=6, null=True, verbose_name='支付密码')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': '用户信息',
                'verbose_name': '用户信息',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名称')),
                ('icon_class', models.CharField(max_length=30, verbose_name='图标样式')),
                ('banner', models.ImageField(upload_to='category/', verbose_name='广告图')),
            ],
            options={
                'verbose_name_plural': '商品分类',
                'verbose_name': '商品分类',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('picture', models.ImageField(upload_to='goods/', verbose_name='主图')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价格')),
                ('desc', models.CharField(max_length=100, verbose_name='描述')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('stock', models.IntegerField(verbose_name='库存')),
                ('detail', models.TextField(verbose_name='详情')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name_plural': '商品信息',
                'ordering': ('-price',),
                'verbose_name': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价格')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name_plural': '订单商品',
                'verbose_name': '订单商品',
            },
        ),
        migrations.CreateModel(
            name='ReceiveAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='所在区域')),
                ('name', models.CharField(max_length=20, verbose_name='收货人')),
                ('detail', models.CharField(max_length=100, verbose_name='详细地址')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('alias', models.CharField(max_length=20, null=True, verbose_name='地址别名')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '收货地址',
                'verbose_name': '收货地址',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '未完成'), (1, '已完成')], verbose_name='订单状态')),
                ('pay_status', models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付')], verbose_name='支付状态')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='订单日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总金额')),
                ('goods', models.ManyToManyField(through='simple.OrderGoods', to='simple.Goods')),
                ('receive_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simple.ReceiveAddress', verbose_name='收货地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '订单信息',
                'verbose_name': '订单信息',
            },
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='orderinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple.OrderInfo', verbose_name='订单'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='数量')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple.Goods', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '购物车',
                'verbose_name': '购物车',
            },
        ),
    ]
