# Generated by Django 2.2.1 on 2019-05-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveaddress',
            name='tel',
            field=models.CharField(default=11111111111, max_length=11, verbose_name='手机'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付')], default=0, verbose_name='支付状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未完成'), (1, '已完成')], default=0, verbose_name='订单状态'),
        ),
    ]
