# Generated by Django 2.2.1 on 2019-05-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0002_auto_20190514_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='pay_status',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='status',
        ),
    ]
