# Generated by Django 2.2.1 on 2019-05-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0003_auto_20190514_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='pay_status',
            field=models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付')], default=0, verbose_name='支付状态'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未完成'), (1, '已完成')], default=0, verbose_name='订单状态'),
        ),
    ]
